'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\ffmpeg\bin\ffmpeg.exe")>  _
        Public Property FfmpegPath() As String
            Get
                Return CType(Me("FfmpegPath"),String)
            End Get
            Set
                Me("FfmpegPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00:02:59")>  _
        Public Property DuracionPredeterminada() As Global.System.TimeSpan
            Get
                Return CType(Me("DuracionPredeterminada"),Global.System.TimeSpan)
            End Get
            Set
                Me("DuracionPredeterminada") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Vídeos|*.mp4;*.avi;*.mkv;*.mov;*.wmv;*.flv;*.webm;*.mpeg;*.mpg;*.m4v;*.3gp;*.ts;*"& _ 
            ".m2ts;*.vob;*.divx;*.ogv;*.asf;*.rm;*.rmvb;*.dat;*.nsv;*.f4v;*.mxf;*.mts;*.m2v;*"& _ 
            ".svi;*.tp;*.m2t;*.iso;*.m2p;*.mpv2;*.vob;*.vro;*.nsv;*.nuv;*.gxf;*.ps;*.rec;*.tt"& _ 
            "s;*.m2ts;*.m2t;*.m2p;*.m2v;*.m2p;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m"& _ 
            "2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*"& _ 
            ".m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2t"& _ 
            "s;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*."& _ 
            "m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;"& _ 
            "*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2"& _ 
            "t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*."& _ 
            "m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts;*.m2v;*.m2t;*.m2ts"& _ 
            ";*.m2v;*.m2t")>  _
        Public Property FiltroVideo() As String
            Get
                Return CType(Me("FiltroVideo"),String)
            End Get
            Set
                Me("FiltroVideo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DirectorioVideos() As String
            Get
                Return CType(Me("DirectorioVideos"),String)
            End Get
            Set
                Me("DirectorioVideos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://sourceforge.net/projects/anunnakiproject/files/ffmpeg.exe/download")>  _
        Public Property Urlffmpeg() As String
            Get
                Return CType(Me("Urlffmpeg"),String)
            End Get
            Set
                Me("Urlffmpeg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://github.com/croketworld/CrearShortDesdeVideo/issues")>  _
        Public Property UrlIssues() As String
            Get
                Return CType(Me("UrlIssues"),String)
            End Get
            Set
                Me("UrlIssues") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Imágenes y documentos|*.*")>  _
        Public Property FiltroAdjuntosReporte() As String
            Get
                Return CType(Me("FiltroAdjuntosReporte"),String)
            End Get
            Set
                Me("FiltroAdjuntosReporte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Adjuntar archivos")>  _
        Public Property FiltroAdjuntos_tituloDialogo() As String
            Get
                Return CType(Me("FiltroAdjuntos_tituloDialogo"),String)
            End Get
            Set
                Me("FiltroAdjuntos_tituloDialogo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("De momento, puedes reportar errores y añadir sigerencias en github")>  _
        Public Property TextoIssues() As String
            Get
                Return CType(Me("TextoIssues"),String)
            End Get
            Set
                Me("TextoIssues") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://github.com/croketworld/CrearShortDesdeVideo")>  _
        Public Property UrlGitHub() As String
            Get
                Return CType(Me("UrlGitHub"),String)
            End Get
            Set
                Me("UrlGitHub") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UrlActualizaciones() As String
            Get
                Return CType(Me("UrlActualizaciones"),String)
            End Get
            Set
                Me("UrlActualizaciones") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Iniciando proceso con comando")>  _
        Public Property Texto_iniciandoComando() As String
            Get
                Return CType(Me("Texto_iniciandoComando"),String)
            End Get
            Set
                Me("Texto_iniciandoComando") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Error ejecutando tarea")>  _
        Public Property Texto_ErrorEjecutandoTarea() As String
            Get
                Return CType(Me("Texto_ErrorEjecutandoTarea"),String)
            End Get
            Set
                Me("Texto_ErrorEjecutandoTarea") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Output de ffmpeg")>  _
        Public Property Texto_outputFfmpeg() As String
            Get
                Return CType(Me("Texto_outputFfmpeg"),String)
            End Get
            Set
                Me("Texto_outputFfmpeg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Error al ejecutar el comando ffpmeg.")>  _
        Public Property Texto_ErrorEjecutandoComandoFfmpeg() As String
            Get
                Return CType(Me("Texto_ErrorEjecutandoComandoFfmpeg"),String)
            End Get
            Set
                Me("Texto_ErrorEjecutandoComandoFfmpeg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Detalles del error")>  _
        Public Property Texto_DetalleDelError() As String
            Get
                Return CType(Me("Texto_DetalleDelError"),String)
            End Get
            Set
                Me("Texto_DetalleDelError") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("El comando ejecutado es")>  _
        Public Property Texto_ComandoEjecutadoEs() As String
            Get
                Return CType(Me("Texto_ComandoEjecutadoEs"),String)
            End Get
            Set
                Me("Texto_ComandoEjecutadoEs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Crear video corto")>  _
        Public Property Btn_CrearVideoCorto() As String
            Get
                Return CType(Me("Btn_CrearVideoCorto"),String)
            End Get
            Set
                Me("Btn_CrearVideoCorto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("cancelado por el usuario")>  _
        Public Property Texto_canceladoPorUsuario() As String
            Get
                Return CType(Me("Texto_canceladoPorUsuario"),String)
            End Get
            Set
                Me("Texto_canceladoPorUsuario") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Resultado de la operación correcta? ")>  _
        Public Property Texto_resultadoCorrectoONo() As String
            Get
                Return CType(Me("Texto_resultadoCorrectoONo"),String)
            End Get
            Set
                Me("Texto_resultadoCorrectoONo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Cancelar")>  _
        Public Property Btn_cancelar() As String
            Get
                Return CType(Me("Btn_cancelar"),String)
            End Get
            Set
                Me("Btn_cancelar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ffmpeg descargado correctamente")>  _
        Public Property Texto_ffmpegDescargado() As String
            Get
                Return CType(Me("Texto_ffmpegDescargado"),String)
            End Get
            Set
                Me("Texto_ffmpegDescargado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Iniciando comprobaciones previas")>  _
        Public Property Texto_IniciandoComprobaciones() As String
            Get
                Return CType(Me("Texto_IniciandoComprobaciones"),String)
            End Get
            Set
                Me("Texto_IniciandoComprobaciones") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Validaciones previas pasadas, iniciando proceso")>  _
        Public Property Texto_validacionesOK() As String
            Get
                Return CType(Me("Texto_validacionesOK"),String)
            End Get
            Set
                Me("Texto_validacionesOK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Duración")>  _
        Public Property Texto_Duracion() As String
            Get
                Return CType(Me("Texto_Duracion"),String)
            End Get
            Set
                Me("Texto_Duracion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("segundos")>  _
        Public Property Texto_Segundos() As String
            Get
                Return CType(Me("Texto_Segundos"),String)
            End Get
            Set
                Me("Texto_Segundos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Descargando ffmpeg..")>  _
        Public Property Texto_DescargandoFffmpeg() As String
            Get
                Return CType(Me("Texto_DescargandoFffmpeg"),String)
            End Get
            Set
                Me("Texto_DescargandoFffmpeg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ffmpeg.exe")>  _
        Public Property Texto_ffmpeg_exe() As String
            Get
                Return CType(Me("Texto_ffmpeg_exe"),String)
            End Get
            Set
                Me("Texto_ffmpeg_exe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsd=""http://www.w3."& _ 
            "org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>\ffmpeg.exe</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>\ffmpeg\ffmpeg.exe</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>\ff"& _ 
            "mpeg\bin\ffmpeg.exe</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public Property Rutas_ffmpeg() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Rutas_ffmpeg"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("Rutas_ffmpeg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("En busca de ")>  _
        Public Property Texto_EnbuscaDe() As String
            Get
                Return CType(Me("Texto_EnbuscaDe"),String)
            End Get
            Set
                Me("Texto_EnbuscaDe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Selecciona el vídeo del que quieres obtener un fragmento")>  _
        Public Property Texto_dialogoSeleccionarVideoOrigenTitulo() As String
            Get
                Return CType(Me("Texto_dialogoSeleccionarVideoOrigenTitulo"),String)
            End Get
            Set
                Me("Texto_dialogoSeleccionarVideoOrigenTitulo") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CrearShortDesdeVideo.My.MySettings
            Get
                Return Global.CrearShortDesdeVideo.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
